name: bloc_morph
description: "A Flutter widget for elegant state management with Bloc, animating transitions between loading, error, empty, and content states."
version: 0.3.7+8
homepage: https://github.com/PuzzleTakX/bloc_morph.git
repository: https://github.com/PuzzleTakX/bloc_morph
issue_tracker: https://github.com/PuzzleTakX/bloc_morph/issues
documentation: https://github.com/PuzzleTakX/bloc_morph/blob/master/README.md
license: https://github.com/PuzzleTakX/bloc_morph/blob/master/LICENSE

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1  # Added explicit version constraint

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
