name: bloc_morph
description: "BlocMorph is a Flutter widget for elegant state management with Bloc. It smoothly animates transitions between loading, error, empty, network error, and content states, providing a beautiful and user-friendly UI experience."
version: 0.1.4
homepage: https://github.com/PuzzleTakX/bloc_morph.git
repository: https://github.com/PuzzleTakX/bloc_morph
issue_tracker: https://github.com/PuzzleTakX/bloc_morph/issues
documentation: https://github.com/PuzzleTakX/bloc_morph/blob/master/README.md
license: https://github.com/PuzzleTakX/bloc_morph/blob/master/LICENSE

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
